### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by fpellicciotti** [barrycarey/Seedbox-Statistics-For-InfluxDB#2]
Everytime I execute the influxdbSeedbox.py, I get the following error message:

Loading Configuration File config.ini
Configuration Successfully Loaded
Logging is enabled.  Log output will be sent to output.log
Generating Deluge Client
Traceback (most recent call last):
  File "influxdbSeedbox.py", line 286, in <module>
    main()
  File "influxdbSeedbox.py", line 282, in main
    monitor.run()
  File "influxdbSeedbox.py", line 264, in run
    self.write_influx_data(torrent_json)
  File "influxdbSeedbox.py", line 237, in write_influx_data
    self.influx_client.write_points(json_data)
  File "C:\Program Files\Python36\lib\site-packages\influxdb\client.py", line 456, in write_points
    tags=tags, protocol=protocol)
  File "C:\Program Files\Python36\lib\site-packages\influxdb\client.py", line 506, in _write_points
    protocol=protocol
  File "C:\Program Files\Python36\lib\site-packages\influxdb\client.py", line 292, in write
    data = make_lines(data, precision).encode('utf-8')
  File "C:\Program Files\Python36\lib\site-packages\influxdb\line_protocol.py", line 126, in make_lines
    point.get('measurement', data.get('measurement'))
AttributeError: 'list' object has no attribute 'get'

I have used Deluge and Utorrent with the same issue.

**Comment by Gibletron** [comment]
A year later I'm encountering the same issue.
@fpellicciotti did you ever find the issue or a possible solution?

I'm using uTorrent specifically and the log seems to say the utorrent.py script is working properly, the writing to influxdb doesn't.
